version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: db_agendador
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: agendador
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: